# -*- coding: utf-8 -*-
"""SimpleGAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D_iCNf_VGo5gTj6xML66VXYk4ERhJIG0
"""

import os
import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.optim as optim

from torch.utils.data import DataLoader
from torchvision import datasets, transforms
from torchvision.utils import make_grid, save_image

import os
import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.optim as optim

from torch.utils.data import DataLoader
from torchvision import datasets, transforms
from torchvision.utils import make_grid, save_image

os.makedirs("outputs", exist_ok=True)
os.makedirs("checkpoints", exist_ok=True)

print("Directories created successfully!")

# ==============================
# Configuration
# ==============================

BATCH_SIZE = 128

IMAGE_SIZE = 28

NOISE_DIM = 100

EPOCHS = 30

LEARNING_RATE = 0.0002

BETA1 = 0.5
BETA2 = 0.999

SAMPLE_INTERVAL = 1

NUM_WORKERS = 2

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Using device:", device)

if device.type == "cuda":
    print("GPU:", torch.cuda.get_device_name(0))

transform = transforms.Compose([
    transforms.ToTensor(),

    transforms.Normalize(
        (0.5,),
        (0.5,)
    )
])

dataset = datasets.MNIST(
    root="./data",
    train=True,
    download=True,
    transform=transform
)

dataloader = DataLoader(
    dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    pin_memory=True
)

print("Dataset size:", len(dataset))
print("Number of batches:", len(dataloader))

images, labels = next(iter(dataloader))

grid = make_grid(
    images[:64],
    nrow=8,
    normalize=True
)

plt.figure(figsize=(8, 8))

plt.imshow(
    grid.permute(1, 2, 0).cpu(),
    cmap="gray"
)

plt.axis("off")
plt.title("Real MNIST Images")

plt.show()

class Generator(nn.Module):

    def __init__(self, noise_dim=100):

        super(Generator, self).__init__()

        self.model = nn.Sequential(

            # 100 → 256
            nn.Linear(noise_dim, 256),
            nn.ReLU(True),

            # 256 → 512
            nn.Linear(256, 512),
            nn.ReLU(True),

            # 512 → 1024
            nn.Linear(512, 1024),
            nn.ReLU(True),

            # 1024 → 784
            nn.Linear(1024, 784),

            # Output range [-1, 1]
            nn.Tanh()
        )

    def forward(self, x):

        x = self.model(x)

        # 784 → 1 × 28 × 28

        x = x.view(
            x.size(0),
            1,
            28,
            28
        )

        return x

class Discriminator(nn.Module):

    def __init__(self):

        super(Discriminator, self).__init__()

        self.model = nn.Sequential(

            # 784 → 1024
            nn.Linear(784, 1024),
            nn.LeakyReLU(
                0.2,
                inplace=True
            ),

            # 1024 → 512
            nn.Linear(1024, 512),
            nn.LeakyReLU(
                0.2,
                inplace=True
            ),

            # 512 → 1
            nn.Linear(512, 1),

            # Probability
            nn.Sigmoid()
        )

    def forward(self, x):

        # 28 × 28 → 784

        x = x.view(
            x.size(0),
            -1
        )

        return self.model(x)

generator = Generator(
    noise_dim=NOISE_DIM
).to(device)

discriminator = Discriminator().to(device)

print("Generator:")
print(generator)

print("\nDiscriminator:")
print(discriminator)

def count_parameters(model):

    return sum(
        p.numel()
        for p in model.parameters()
        if p.requires_grad
    )


print(
    "Generator parameters:",
    count_parameters(generator)
)

print(
    "Discriminator parameters:",
    count_parameters(discriminator)
)

def count_parameters(model):

    return sum(
        p.numel()
        for p in model.parameters()
        if p.requires_grad
    )


print(
    "Generator parameters:",
    count_parameters(generator)
)

print(
    "Discriminator parameters:",
    count_parameters(discriminator)
)

optimizer_G = optim.Adam(
    generator.parameters(),
    lr=LEARNING_RATE,
    betas=(BETA1, BETA2)
)

optimizer_D = optim.Adam(
    discriminator.parameters(),
    lr=LEARNING_RATE,
    betas=(BETA1, BETA2)
)

print("Optimizers created successfully!")

fixed_noise = torch.randn(
    64,
    NOISE_DIM,
    device=device
)

print("Fixed noise shape:", fixed_noise.shape)

generator.eval()

with torch.no_grad():

    fake_images = generator(
        fixed_noise
    )

grid = make_grid(
    fake_images,
    nrow=8,
    normalize=True
)

plt.figure(figsize=(8, 8))

plt.imshow(
    grid.permute(1, 2, 0).cpu(),
    cmap="gray"
)

plt.axis("off")
plt.title("Generated Images Before Training")

plt.show()

# ============================================================
# Training
# ============================================================

criterion = nn.BCELoss()

g_losses = []
d_losses = []

print("=" * 60)
print("Starting GAN Training")
print("=" * 60)

for epoch in range(1, EPOCHS + 1):

    generator.train()
    discriminator.train()

    total_g_loss = 0.0
    total_d_loss = 0.0

    for batch_index, (real_images, _) in enumerate(dataloader):

        # Move real images to GPU
        real_images = real_images.to(
            device,
            non_blocking=True
        )

        batch_size = real_images.size(0)

        # ----------------------------------------------------
        # Labels
        # ----------------------------------------------------

        real_labels = torch.ones(
            batch_size,
            1,
            device=device
        )

        fake_labels = torch.zeros(
            batch_size,
            1,
            device=device
        )

        # ====================================================
        # Train Discriminator
        # ====================================================

        optimizer_D.zero_grad()

        # ----------------------------------------------------
        # Real images
        # ----------------------------------------------------

        real_output = discriminator(
            real_images
        )

        real_loss = criterion(
            real_output,
            real_labels
        )

        # ----------------------------------------------------
        # Generate fake images
        # ----------------------------------------------------

        noise = torch.randn(
            batch_size,
            NOISE_DIM,
            device=device
        )

        fake_images = generator(noise)

        # ----------------------------------------------------
        # Fake images
        # ----------------------------------------------------

        fake_output = discriminator(
            fake_images.detach()
        )

        fake_loss = criterion(
            fake_output,
            fake_labels
        )

        # ----------------------------------------------------
        # Total discriminator loss
        # ----------------------------------------------------

        d_loss = real_loss + fake_loss

        d_loss.backward()

        optimizer_D.step()

        # ====================================================
        # Train Generator
        # ====================================================

        optimizer_G.zero_grad()

        # Generate new noise
        noise = torch.randn(
            batch_size,
            NOISE_DIM,
            device=device
        )

        fake_images = generator(noise)

        fake_output = discriminator(
            fake_images
        )

        # Generator wants fake images
        # to be classified as REAL

        g_loss = criterion(
            fake_output,
            real_labels
        )

        g_loss.backward()

        optimizer_G.step()

        # ----------------------------------------------------
        # Track losses
        # ----------------------------------------------------

        total_d_loss += d_loss.item()
        total_g_loss += g_loss.item()

    # ========================================================
    # Average losses
    # ========================================================

    avg_d_loss = (
        total_d_loss / len(dataloader)
    )

    avg_g_loss = (
        total_g_loss / len(dataloader)
    )

    d_losses.append(avg_d_loss)
    g_losses.append(avg_g_loss)

    # ========================================================
    # Print progress
    # ========================================================

    print(
        f"Epoch [{epoch:02d}/{EPOCHS}] | "
        f"D Loss: {avg_d_loss:.4f} | "
        f"G Loss: {avg_g_loss:.4f}"
    )

    # ========================================================
    # Generate sample images
    # ========================================================

    generator.eval()

    with torch.no_grad():

        generated_images = generator(
            fixed_noise
        )

    save_image(
        generated_images,
        f"outputs/epoch_{epoch:03d}.png",
        nrow=8,
        normalize=True
    )

    # ========================================================
    # Save checkpoints
    # ========================================================

    torch.save(
        generator.state_dict(),
        "checkpoints/generator_latest.pth"
    )

    torch.save(
        discriminator.state_dict(),
        "checkpoints/discriminator_latest.pth"
    )

print()
print("=" * 60)
print("Training completed!")
print("=" * 60)

generator.eval()

with torch.no_grad():

    generated_images = generator(
        fixed_noise
    )

grid = make_grid(
    generated_images,
    nrow=8,
    normalize=True
)

plt.figure(figsize=(10, 10))

plt.imshow(
    grid.permute(1, 2, 0).cpu(),
    cmap="gray"
)

plt.axis("off")

plt.title(
    "Generated MNIST Digits After Training"
)

plt.show()